#!/bin/bash
#
# This is /sbin/ykluks-keyscript, which gets called when unlocking the disk
#

# Set this in case the value is missing in /etc/ykluks.cfg
CONCATENATE=0
HASH=0
WELCOME_TEXT="Please insert YubiKey and press enter or enter a valid LUKS2 password ..."
CHALLENGE_TEXT="Please enter a valid YubiKey passphrase ..."
YUBIKEY_SLOT=2
# YUBIKEY_CHALLENGE="YubiKey Challenge" Set this in /etc/ykluks.conf to enable 1FA

# Import config
if [ -f /etc/ykluks.cfg ]
then
    # shellcheck source=ykluks.cfg
    . /etc/ykluks.cfg
fi

Message() {
    if [ -x /bin/plymouth ] && plymouth --ping
    then
        plymouth message --text="$*"
    else
        echo "$@" >&2
    fi
    return
}

Debug () {
    if [ -n "$DEBUG" ]
    then
        Message "$@"
    fi
}

Password () {
    if [ -x /bin/plymouth ] && plymouth --ping
    then
        PASSWORD="$(plymouth ask-for-password --prompt "$WELCOME_TEXT")"
    else
        PASSWORD="$(/lib/cryptsetup/askpass "$WELCOME_TEXT")"
    fi

    if [ -z "$PASSWORD" ]
    then
        if [ "$(ykinfo -q -"$YUBIKEY_SLOT")" != "1" ]
        then
            Message "LUKS2 password cant be blank, please try again"
        else
            Debug "YubiKey detected, restart script to handle YubiKey authentication"
        fi
        exit
    fi

    echo -n "$PASSWORD"
    exit
}

Challenge () {
    if [ -x /bin/plymouth ] && plymouth --ping
    then
        YUBIKEY_CHALLENGE="$(plymouth ask-for-password --prompt "$CHALLENGE_TEXT")"
    else
        YUBIKEY_CHALLENGE="$(/lib/cryptsetup/askpass "$CHALLENGE_TEXT")"
    fi

    if [ -z "$YUBIKEY_CHALLENGE" ]
    then
        Message "YubiKey challenge cant be blank, please try again"
        exit
    fi
}

DEBUG=true

# Check if 1FA is not enabled
# Check if YubiKey is missing 
# Ask user for 2FA challenge, LUKS2 password or to Insert YubiKey
if [ -z "$YUBIKEY_CHALLENGE" ] || [ "$(ykinfo -q -"$YUBIKEY_SLOT" 2> /dev/null)" != "1" ]
then
    if [ "$(ykinfo -q -"$YUBIKEY_SLOT" 2> /dev/null)" = "1" ]
    then
        Debug "Configured YubiKey detected"
        Challenge
    else
        Debug "Ask for Password or insert YubuKey"
        Password
    fi
else
    Debug "1FA enabled $YUBIKEY_CHALLENGE"
fi

# Check if YubiKey has been inserted during promt
if [ "$(ykinfo -q -"$YUBIKEY_SLOT" 2> /dev/null)" = "1" ]
then
    Message "Accessing yubikey..."
    if [ "$HASH" = "1" ]
    then
        CHALLENGE=$(echo -n "$YUBIKEY_CHALLENGE" | sha256sum | awk '{print $1}')
    else
        CHALLENGE=$YUBIKEY_CHALLENGE
    fi
    RESPONCE="$(echo -n "$CHALLENGE" | ykchalresp -"$YUBIKEY_SLOT" -i- 2>/dev/null || true)"
    if [ "$RESPONCE" ]
    then
        Message "Retrieved the response from the Yubikey"
        if [ "$CONCATENATE" = "1" ]
        then
            echo -n "$CHALLENGE$RESPONCE"
        else
            echo -n "$RESPONCE"
        fi
    else
        Message "Failed to retrieve the response from the Yubikey"
    fi
fi

exit
