#! /bin/sh
#
# This is /sbin/ykluks-keyscript, which gets called when unlocking the disk
#
YUBIKEY_SLOT=2 #Set this in case the value is missing in /etc/ykluks.cfg

. /etc/ykluks.cfg

if [ -z "$WELCOME_TEXT" ]
then
    WELCOME_TEXT="Please insert yubikey and press enter or enter a valid passphrase"
fi

message()
{
    if [ -x /bin/plymouth ] && plymouth --ping
    then
        plymouth message --text="$*"
    else
        echo "$@" >&2
    fi
    return 0
}

# Check if YubiKey is missing or 1FA is enabled
if [ -z "$YUBIKEY_CHALLENGE" ] || ! ykinfo -q -"$YUBIKEY_SLOT" >/dev/null 2>&1
then
	if [ -x /bin/plymouth ] && plymouth --ping
	then
		PASSWORD="$(plymouth ask-for-password --prompt "$WELCOME_TEXT")"
	else
		PASSWORD="$(/lib/cryptsetup/askpass "$WELCOME_TEXT")"
	fi
    if [ -z "$cryptkeyscript" ]
fi

# Check if user has press enter after inserting YubiKey (remove 1FA warning)
if [ -z "$PASSWORD" ] && [ -n "$YUBIKEY_CHALLENGE" ]
then
	CHALLENGE="$YUBIKEY_CHALLENGE"
fi

# Check if YubiKey has been inserted during promt
if ykinfo -q -"$YUBIKEY_SLOT" > /dev/null 2>&1
then
    message "Accessing yubikey..."
    if [ "$HASH" = "1" ]
    then
        PASSWORD=$(printf %s "$PASSWORD" | sha256sum | awk '{print $1}')
    fi
    RESPONCE="$(printf %s "$PASSWORD" | ykchalresp -"$YUBIKEY_SLOT" -i- 2>/dev/null || true)"
    if [ "$RESPONCE" ]
    then
        message "Retrieved the response from the Yubikey"
        if [ "$CONCATENATE" = "1" ]
        then
            printf '%s' "$PASSWORD$RESPONCE"
        else
            printf '%s' "$RESPONCE"
        fi
    else
        message "Failed to retrieve the response from the Yubikey"
    fi
else
    printf '%s' "$PASSWORD"
fi

exit 0
